trigger: none
pr:
  branches:
    include:
      - main

pool:
  vmImage: "ubuntu-latest"

steps:
  - script: |
      sudo apt-get update
      sudo apt-get install apt-transport-https
      sudo sh -c 'wget -qO- https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -'
      sudo sh -c 'wget -qO- https://storage.googleapis.com/download.dartlang.org/linux/debian/dart_stable.list > /etc/apt/sources.list.d/dart_stable.list'
      sudo apt-get update
      sudo apt-get install dart
    displayName: "Install Dart SDK"

  - template: build_and_test_template.yaml
    parameters:
      libraryPath: "dependency_injection/zef_di_abstractions"

  - template: build_and_test_template.yaml
    parameters:
      libraryPath: "dependency_injection/zef_di_inglue"
