name: zef_di_inglue
description: A starting point for Dart libraries or applications.
version: 0.0.1
repository: https://github.com/zooper-lib/Zooper.Effortless.Flutter

environment:
  sdk: ">=3.0.0-417 <4.0.0"

# Add regular dependencies here.
dependencies:
  any_of: ^2.0.0

  zef_di_abstractions:
    path: ../zef_di_abstractions

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
