targets:
  $default:
    builders:
      zooper_effortless_flutter_ddd_generator|handlerGeneratorBuilder:
        enabled: true

builders:
  handlerGeneratorBuilder:
    import: "package:zooper_effortless_flutter_ddd_generator/zooper_effortless_flutter_ddd_generator.dart"
    builder_factories: ["handlerGeneratorBuilder"]
    build_extensions: { ".dart": [".generated.dart"] }
    build_to: source
    auto_apply: dependents
    applies_builders: ["source_gen|combining_builder"]
