name: zef_di_abstractions
description: A starting point for Dart libraries or applications.
version: 0.0.1
repository: https://github.com/zooper-lib/Zooper.Effortless.Flutter

environment:
  sdk: ^3.2.6

dependencies:
  any_of: ^1.1.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
