name: PR Workflow

on:
  pull_request:
    branches: [main, develop]

jobs:
  dart_workflow:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - PROJECT_NAME: zef_di_abstractions
            PROJECT_DIR2: dependency_injection
            PROJECT_PATH: dependency_injection/zef_di_abstractions

    env:
      PROJECT_DIR: ${{ matrix.PROJECT_PATH }}

    steps:
      - uses: actions/checkout@v2
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: stable

      - name: Install dependencies
        run: dart pub get

      - name: Run dart analyze
        run: dart analyze

      - name: Run tests
        run: dart test
